name: UnitTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Use the Node.js version that matches your development environment

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint  # Assuming you have a lint script in your package.json

      - name: Run Tests
        run: npm test  # This will execute your test suite, assuming it's configured under "npm test" in your package.json
